### ISSUE TITLE
MDLV3000Reader

### ISSUE THREAD

**Issue by marco-foscato** [denoptim-project/DENOPTIM#131]
Need to switch to MDLV3000Reader depending on content. Attempt to read the attached
[dg_568.json](https://github.com/denoptim-project/DENOPTIM/files/13917542/dg_568.json)
hits the limits of V2000 SDF files, so, mu must implement the switch to V3000 as a catch for exception:

```
org.openscience.cdk.io.MDLV2000Reader ERROR: Error while parsing line 4:   0  0  0     0  0            999 V3000 -> This file must be read with the MDLV3000Reader.
org.openscience.cdk.exception.CDKException: Only supports AtomContainer objects.
	at org.openscience.cdk.io.MDLV3000Reader.read(MDLV3000Reader.java:154)
	at denoptim.io.DenoptimIO.readAllAtomContainers(DenoptimIO.java:329)
	at denoptim.gui.MoleculeViewPanel.loadChemicalStructureFromFile(MoleculeViewPanel.java:339)
	at denoptim.gui.MoleculeViewPanel.loadChemicalStructure(MoleculeViewPanel.java:281)
	at denoptim.gui.GraphVertexMolViewerPanel.loadDnGraphToViewer(GraphVertexMolViewerPanel.java:250)
	at denoptim.gui.GUIGraphHandler.loadCurrentGraphIdxToViewer(GUIGraphHandler.java:1829)
	at denoptim.gui.GUIGraphHandler.importGraphsFromFile(GUIGraphHandler.java:1550)
	at denoptim.gui.MainToolBar.openFile(MainToolBar.java:502)
	at denoptim.gui.GUI.run(GUI.java:192)
...
```

**Comment by marco-foscato** [comment]
closed by 935d956
